In [83]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

1. How likely is it that you roll doubles when rolling two dice?


In [84]:
# generate the numbers
# reshape to the structure we want
# pd.Series.data.reshape((2,100))
# apply a condition to get a boolean, convert to int
# calculate liklihood (num of [1,1] over total sets)

n_col = 2
n_row = 100000
rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_row * n_col).reshape(n_row,n_col)

doubles = rolls[:,0] == rolls[:,1]
doubles
doubles.astype(int)

type(doubles)

df = pd.DataFrame(rolls, columns = ['Coin_1','Coin_2'])
df_doubles = pd.DataFrame(doubles)
df_doubles


0
0       True
1      False
2      False
3      False
4      False
...      ...
99995  False
99996  False
99997  False
99998  False
99999  False

[100000 rows x 1 columns]

In [85]:
df_doubles.astype(int)
actual_doubles = df_doubles.sum()

prob_of_doubles = actual_doubles / df_doubles.count()
prob_of_doubles

#Probability of rolling doubles is 0.168 or 16.8%


0    0.16799
dtype: float64

Solution to Execerise 1 as a function below:

In [86]:
n_col = 2
n_row = 100000

def probability_of_doubles(n_row,n_col):
    rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_row * n_col).reshape(n_row,n_col)
    doubles = rolls[:,0] == rolls[:,1]
    doubles.astype(int)
    df = pd.DataFrame(rolls, columns = ['Coin_1','Coin_2']) 
    df_doubles = pd.DataFrame(doubles)
    df_doubles.astype(int)
    actual_doubles = df_doubles.sum()
    prob_of_doubles = actual_doubles / df_doubles.count()
    return prob_of_doubles

Exercise 2:


2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?


In [87]:
# 8 coins total
# part 1: find prob of 3 heads, no more no less
# part 2: find prob of more than 3 heads

# each coin either heads or tails 1 for heads 2 for tails
# can i reuse a lot of code from the previous exercise?

num_total_flips = 100000
num_coins = 8 #rename/flip roles for better readability

flips = np.random.choice([0,1], num_total_flips * num_coins).reshape(num_total_flips,num_coins)
# heads = flips[:,0] == rolls[:,1]
# doubles.astype(int)
# first_df = pd.DataFrame(flips, columns = ['coin_1, coin_2, coin_3, coin_4, coin_5, coin_6, coin_7, coin_8']) 
# df_doubles = pd.DataFrame(doubles)
# df_doubles.astype(int)
# actual_doubles = df_doubles.sum()
# prob_of_doubles = actual_doubles / df_doubles.count()


#how do I index an entire row? flips[:,:]? 

# flips[:].sum() # need this to calculate for each row n_coins

# if flips[n].sum() == 3:


#I want each row in flips to be summed and compared to == 3 for boolean series
#convert boolean series to int and sum, this gets the total number of sets that are == 3 heads
# use same code for part 2 except sum > 3

is_3_heads = 0

flips_int = flips.astype(int)
flips_pd_df = pd.DataFrame(flips, columns = ['coin_1', 'coin_2', 'coin_3', 'coin_4', 'coin_5', 'coin_6', 'coin_7', 'coin_8']) 
flips_pd_df





coin_1  coin_2  coin_3  coin_4  coin_5  coin_6  coin_7  coin_8
0           0       1       1       0       0       0       0       0
1           0       1       1       0       0       0       1       1
2           1       0       1       1       0       1       1       1
3           0       1       1       0       1       1       0       0
4           1       1       0       1       1       1       0       1
...       ...     ...     ...     ...     ...     ...     ...     ...
99995       1       1       1       0       0       1       0       0
99996       0       1       1       1       0       1       1       0
99997       1       0       1       0       0       1       0       0
99998       0       1       1       0       1       1       0       0
99999       1       0       1       0       0       1       1       1

[100000 rows x 8 columns]

In [88]:
num_heads_per_set = flips.sum(axis = 1)
num_heads_per_set #this is a np array totaling each set of 8 coin flips
#how do I apply a condition to get booleans == 3?
num_heads_per_set_pdSer = pd.Series(num_heads_per_set)
num_heads_per_set_pdSer





0        2
1        4
2        6
3        4
4        6
        ..
99995    4
99996    5
99997    3
99998    4
99999    5
Length: 100000, dtype: int64

In [89]:
#initialize a variable to count num of rows that meet condition == 3
# or create a new series of only rows equal to 3 then count the rows .count()

is_1_if_3_heads = (num_heads_per_set_pdSer == 3).astype(int)

total_sets_with_3_heads = is_1_if_3_heads.sum() #22 sets are == 3

prob_of_exactly_3_heads = total_sets_with_3_heads / num_heads_per_set_pdSer.count()
prob_of_exactly_3_heads








0.21956

Solution to #2 below:

In [90]:
# put it all together for better readability

num_total_flips = 100000
num_coins = 8

flips = np.random.choice([0,1], num_total_flips * num_coins).reshape(num_total_flips,num_coins)
flips_int = flips.astype(int)
flips_pd_df = pd.DataFrame(flips, columns = ['coin_1', 'coin_2', 'coin_3', 'coin_4', 'coin_5', 'coin_6', 'coin_7', 'coin_8']) 
num_heads_per_set = flips.sum(axis = 1)
num_heads_per_set_pdSer = pd.Series(num_heads_per_set)
is_1_if_3_heads = (num_heads_per_set_pdSer == 3).astype(int)
total_sets_with_3_heads = is_1_if_3_heads.sum()
prob_of_exactly_3_heads = total_sets_with_3_heads / num_heads_per_set_pdSer.count()
prob_of_exactly_3_heads

#can format the solution to show as a percentage rounded to 2 decimals for better radability




0.21951

In [91]:
(prob_of_exactly_3_heads * 100).round(2).astype(str) + '%'
#formatted, can not use like this for more calculations 

'21.95%'

In [92]:
#same thing but greater than 3 heads

num_total_flips = 100000
num_coins = 8

flips = np.random.choice([0,1], num_total_flips * num_coins).reshape(num_total_flips,num_coins)
flips_int = flips.astype(int)
flips_pd_df = pd.DataFrame(flips, columns = ['coin_1', 'coin_2', 'coin_3', 'coin_4', 'coin_5', 'coin_6', 'coin_7', 'coin_8']) 
num_heads_per_set = flips.sum(axis = 1)
num_heads_per_set_pdSer = pd.Series(num_heads_per_set)
is_1_if_3_heads = (num_heads_per_set_pdSer > 3).astype(int)
total_sets_with_3_heads = is_1_if_3_heads.sum()
prob_of_exactly_3_heads = total_sets_with_3_heads / num_heads_per_set_pdSer.count()
prob_of_exactly_3_heads

0.63316


3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?


In [93]:
num_trials = 100000
possible_outcomes = ['wd', 'wd', 'wd', 'ds']
num_billboards = 2
billboards = np.random.choice(possible_outcomes, size=(num_trials,num_billboards))
billboards



array([['wd', 'ds'],
       ['wd', 'wd'],
       ['wd', 'wd'],
       ...,
       ['wd', 'wd'],
       ['wd', 'wd'],
       ['wd', 'wd']], dtype='<U2')

In [94]:
(billboards == 'ds').sum(axis=1)
prob_both_ds = ((billboards == 'ds').sum(axis=1) == 2).mean()
prob_both_ds


0.0626


4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values


In [95]:
sd = 1.5
mean = 3
num_days = 5
poptarts_sold_in_a_day= np.random.normal(mean, sd, size=(num_trials, num_days))
poptarts_sold_in_a_day


array([[ 0.8361835 ,  3.09689122,  3.92217185,  0.98525606,  3.5649651 ],
       [ 4.28064161,  0.85540647,  2.35383297,  3.77254036,  4.18796248],
       [ 3.92896972,  0.70217044,  5.598192  ,  2.72873122,  4.32368652],
       ...,
       [ 1.96518801,  1.23675756,  2.24492377,  4.44270915,  4.0008089 ],
       [ 1.94064608,  4.20702501, -0.74310552,  5.48761062,  6.78306847],
       [ 3.91765079,  2.7671123 , -1.26556784,  5.14175873,  4.04536831]])

In [96]:
poptarts_sold_in_a_week = poptarts_sold_in_a_day.sum(axis=1)
poptarts_sold_in_a_week
(poptarts_sold_in_a_week < 17).mean()

0.7225


5. Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?



In [97]:
men_avg = 178
men_std = 8
men_height = np.random.normal(men_avg, men_std, num_trials)


In [98]:
women_avg = 170
women_std = 6
women_height = np.random.normal(women_avg, women_std, num_trials)


In [99]:
men_height

array([166.92118426, 164.96630061, 181.33444036, ..., 182.45862096,
       173.7130597 , 172.03623824])

In [100]:
women_height

array([156.78657366, 171.03371577, 169.74688234, ..., 174.86643376,
       172.26990189, 173.50687747])

In [101]:
(women_height > men_height).mean()
#answer

0.21116


6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

- What is the probability that we observe an installation issue within the first 150 students that download anaconda?

- How likely is it that 450 students all download anaconda without an issue?



7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?


In [102]:
num_park_days = 3
truck_in_park = np.random.choice([0, 1], size = (num_trials, num_park_days), p = [0.3, 0.7])
truck_in_park

array([[1, 1, 0],
       [1, 0, 1],
       [1, 0, 1],
       ...,
       [0, 1, 0],
       [1, 1, 0],
       [0, 1, 1]])

In [103]:
type(truck_in_park)

numpy.ndarray

In [104]:
num_trucks = truck_in_park.sum(axis = 1)
num_trucks

array([2, 2, 2, ..., 1, 2, 2])

In [105]:
(num_trucks == 0).mean()
#answer

0.02745


8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [106]:
dates = range(0,365)
num_classmates = 23
birthdays= np.random.choice(dates, size=(num_trials, num_classmates))
birthdays
birthdays = pd.DataFrame(birthdays)
birthdays

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0      297  345  240   38    0   82   80  217  336   33  ...   21   54   83   
1      294  268  233   22  118  128  341  113  265  146  ...   96  120  304   
2      244   18  197  114  172  197  331   78  358  345  ...  357   52  251   
3      119  112  243   70  346  166   24  303  153  317  ...  299  203   70   
4      296  164   31  213  145  265  172   23   64    1  ...   39   54  245   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995  256  316  252  123  307  257   23   77  315  338  ...  236  348  141   
99996  262   30  178   25  352   40  128  232  299   52  ...  263  250   39   
99997   71   63   80  222  122  309  249  241  206   60  ...  260   40  349   
99998  116   22  355  122  137   32  353  257  110   92  ...    0  320  336   
99999  271  191  171  109  197  204  331  349  302  261  ...  265  306  272   

        16   17   18   19   20   21   22  
0      208  161  192  132  223   56   44  
1       49   50  118   24  100  276  238  
2      270  295  250   46   93  144  151  
3      245   67  245  179  345  211  136  
4      352  321   48   62   49   69   43  
...    ...  ...  ...  ...  ...  ...  ...  
99995  119   72  232  331  201  308   71  
99996   64  101  147  156  283  264   38  
99997  119  356  181  127  243  193  344  
99998  208  135   59  250   93  142  275  
99999  133  255   52  187   11  289   95  

[100000 rows x 23 columns]

In [107]:
is_same_bday = (birthdays.nunique(axis=1) < 23)
is_same_bday

0        False
1         True
2         True
3         True
4        False
         ...  
99995    False
99996    False
99997    False
99998    False
99999    False
Length: 100000, dtype: bool

In [108]:
prob_of_same_bday = is_same_bday.mean()
prob_of_same_bday
#answer

0.50605